# Generated by Django 2.2 on 2019-04-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilesApi', '0003_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilesApi.Speaker')),
            ],
        ),
    ]
